# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-21 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_auto_20171207_0259"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationMembers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=10)),
                (
                    "user_email",
                    models.CharField(db_index=True, max_length=255, null=True),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Association Members",
                "verbose_name_plural": "Association Members",
            },
        ),
        migrations.CreateModel(
            name="OrganizationSlider",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("image_s3_urls", models.TextField(null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Association Sliders",
                "verbose_name_plural": "Association Sliders",
            },
        ),
        migrations.CreateModel(
            name="OrgShortCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=10)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Association Shortcodes",
                "verbose_name_plural": "Association Shortcodes",
            },
        ),
        migrations.CreateModel(
            name="SponsoringCompany",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name=b"Long name"
                    ),
                ),
                ("short_name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField()),
                ("logo_url", models.CharField(db_index=True, max_length=255)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Sponsoring Company",
                "verbose_name_plural": "Sponsoring Company",
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="sponsoring_company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.SponsoringCompany",
            ),
        ),
    ]
