# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-28 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_auto_20181221_0335"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmembers",
            name="course_ids",
            field=models.CharField(db_index=True, default="course", max_length=250),
            preserve_default=False,
        ),
    ]
