# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-05 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_organizationmembers_course_ids"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "verbose_name": "Associations",
                "verbose_name_plural": "Associations",
            },
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
