# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-05 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0010_auto_20190305_0155"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="logo_url",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
