# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-05 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0011_auto_20190305_0157"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="logo_url",
            new_name="logo",
        ),
    ]
