# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-03 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0013_organization_org_promo_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="homepage_in_network_with",
            field=models.BooleanField(default=False),
        ),
    ]
