# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-19 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0014_organization_homepage_in_network_with"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="marketing_display",
            field=models.BooleanField(default=True),
        ),
    ]
