# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-17 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0015_organization_marketing_display"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationmembers",
            name="course_ids",
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
