# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-09-30 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0016_auto_20200517_0549"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization_sub_admins",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "user_email",
                    models.CharField(db_index=True, max_length=255, null=True),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("course_id", models.CharField(db_index=True, max_length=500)),
                ("state_ids", models.CharField(db_index=True, max_length=500)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Association Sub Admin",
                "verbose_name_plural": "Association Members",
            },
        ),
    ]
