# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-09-30 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0017_organization_sub_admins"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization_sub_admins",
            options={
                "verbose_name": "Association Sub Admin",
                "verbose_name_plural": "Association Subadmin",
            },
        ),
    ]
