# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-10-01 07:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0018_auto_20200930_0226"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization_sub_admins",
            name="state_ids",
            field=models.CharField(
                max_length=500, validators=[django.core.validators.int_list_validator]
            ),
        ),
    ]
