# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-10-01 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0019_auto_20201001_0357"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization_sub_admins",
            name="state_ids",
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
