# Generated by Django 2.2.18 on 2021-02-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0020_auto_20201001_0716"),
        ("organizations", "0007_historicalorganization"),
    ]

    operations = []
