# Generated by Django 2.2.18 on 2021-02-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0021_merge_20210217_1308"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="short_name",
            field=models.CharField(
                db_index=True,
                help_text="Please do not use spaces or special characters. Only allowed special characters are period (.), hyphen (-) and underscore (_).",
                max_length=255,
                verbose_name="Short Name",
            ),
        ),
        migrations.AlterField(
            model_name="organizationcourse",
            name="course_id",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Course ID"
            ),
        ),
        migrations.AlterField(
            model_name="sponsoringcompany",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Long name"
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalOrganization",
        ),
    ]
