# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-05-28 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCourseOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='program_name')),
                ('program_image', models.ImageField(upload_to=b'program_images/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('enrollment_start_date', models.DateTimeField()),
                ('enrollment_end_date', models.DateTimeField()),
                ('short_description', models.TextField(default=b'describe budle details')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('currency', models.CharField(max_length=255, verbose_name='currency')),
                ('efforts', models.CharField(max_length=255, verbose_name='efforts')),
                ('courses', models.ManyToManyField(related_name='programaddes', to='custom_programs.CustomCourseOverview')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('program', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='custom_programs.ProgramAdd')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user', 'program'),
            },
        ),
        migrations.CreateModel(
            name='ProgramOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('item_name', models.CharField(max_length=255, verbose_name='item_name')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('currency', models.CharField(max_length=255, verbose_name='currency')),
                ('discount_price', models.IntegerField(default=0, verbose_name='Discount Price')),
                ('status', models.CharField(blank=True, choices=[(b'initial', b'Initial'), (b'paying', b'Paying'), (b'paid', b'Paid')], max_length=255, null=True)),
                ('payment_id', models.CharField(max_length=255, verbose_name='payment reciept numnber')),
                ('payment_reference', models.CharField(max_length=255, verbose_name='payment_reference')),
                ('payment_response', jsonfield.fields.JSONField()),
                ('program', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='custom_programs.ProgramAdd')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='programenrollment',
            unique_together=set([('user', 'program')]),
        ),
    ]
