# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-06-22 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('custom_programs', '0002_auto_20210602_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCouponOnebyone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('discout_percentage', models.IntegerField(default=0, verbose_name='Discount Percentage')),
                ('coupon_name', models.CharField(max_length=255, verbose_name='coupon_name')),
                ('coupon_description', models.TextField(default=b'Coupon Description')),
                ('activation_date', models.DateTimeField(blank=True)),
                ('expiration_date', models.DateTimeField(blank=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('number_of_code', models.IntegerField(default=0, verbose_name='Number of Usage')),
                ('program', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='custom_programs.ProgramAdd')),
            ],
            options={
                'ordering': ('coupon_name', 'program'),
            },
        ),
        migrations.AddField(
            model_name='programcoupon',
            name='coupon_onebyone',
            field=models.CharField(blank=True, max_length=255, verbose_name='coupon onebyone'),
        ),
        migrations.AddField(
            model_name='programcoupon',
            name='coupon_type',
            field=models.CharField(blank=True, choices=[(b'onebyone', b'OnebyOne'), (b'onebymultiple', b'Onebymultiple')], max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='programcoupononebyone',
            unique_together=set([('coupon_name', 'program')]),
        ),
    ]
