# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-25 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="awards",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("year", models.PositiveSmallIntegerField(null=True)),
                ("award_image_path", models.CharField(blank=True, max_length=555)),
            ],
        ),
        migrations.CreateModel(
            name="clinic_hospital_address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=255)),
                ("clinic_hospital_name", models.CharField(max_length=255)),
                ("address_line1", models.CharField(blank=True, max_length=1000)),
                ("address_line2", models.CharField(blank=True, max_length=1000)),
                ("address_line3", models.CharField(blank=True, max_length=1000)),
                ("phone_number", models.CharField(blank=True, max_length=25)),
                ("website", models.CharField(blank=True, max_length=255)),
                ("timings", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="education",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=255)),
                ("year", models.PositiveSmallIntegerField(null=True)),
                ("institution_name", models.CharField(max_length=255)),
                ("certificate_path", models.CharField(blank=True, max_length=555)),
                ("description", models.CharField(blank=True, max_length=555)),
            ],
        ),
        migrations.CreateModel(
            name="media_featured",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("media_name", models.CharField(blank=True, max_length=555)),
                ("media_link", models.CharField(max_length=255)),
                ("img", models.CharField(blank=True, max_length=555)),
            ],
        ),
        migrations.CreateModel(
            name="research_papers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, max_length=555)),
                ("pdf_path", models.CharField(blank=True, max_length=555)),
                ("extarnal_link", models.CharField(max_length=255)),
            ],
        ),
    ]
