# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-31 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile_extrainfo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="healthcare_awareness_videos",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=255)),
                ("video_url", models.CharField(max_length=500)),
                ("active", models.CharField(max_length=10)),
            ],
        ),
    ]
