# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-24 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile_extrainfo", "0002_healthcare_awareness_videos"),
    ]

    operations = [
        migrations.CreateModel(
            name="experience",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=255)),
                ("year", models.PositiveSmallIntegerField(null=True)),
                ("institution_name", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, max_length=555)),
            ],
        ),
    ]
