# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-24 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile_extrainfo", "0003_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="year",
            field=models.CharField(default=2014, max_length=255),
            preserve_default=False,
        ),
    ]
