# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-10 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile_extrainfo", "0004_auto_20200124_0304"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic_hospital_address",
            name="phone_number",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="clinic_hospital_address",
            name="timings",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
