# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-28 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile_extrainfo", "0005_auto_20200810_0953"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clinic_hospital_address",
            old_name="timings",
            new_name="timing_1",
        ),
        migrations.AddField(
            model_name="clinic_hospital_address",
            name="timing_2",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="clinic_hospital_address",
            name="timing_3",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="clinic_hospital_address",
            name="timing_4",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
