# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-28 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile_extrainfo", "0006_auto_20200828_0129"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clinic_hospital_address",
            old_name="timing_1",
            new_name="timings",
        ),
    ]
