# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-07 04:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('otp', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[(b'unused', 'Unused'), (b'used', 'Used'), (b'verified', 'Verfied'), (b'expired', 'expired')], max_length=30)),
                ('secret', models.CharField(help_text=b'Secret key used for veryfying otp', max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='otpmanagement',
            unique_together=set([('otp', 'status', 'secret')]),
        ),
    ]
