# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-14 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reg_form", "0002_auto_20190725_0716"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrafields",
            name="medical_philosophy",
            field=models.CharField(
                blank=True,
                default=b"He who studies medicine without books sails an uncharted sea, but he who studies medicine without patients does not go to sea at all.",
                max_length=350,
            ),
        ),
    ]
