# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-03 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reg_form", "0003_auto_20190814_0613"),
    ]

    operations = [
        migrations.AddField(
            model_name="extrafields",
            name="user_seo_url",
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
