# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-11 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reg_form", "0004_extrafields_user_seo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrafields",
            name="user_type",
            field=models.CharField(
                choices=[
                    (b"dr", b"Doctor"),
                    (b"u", b"User"),
                    (b"ms", b"Medical Student"),
                    (b"hc", b"Health Care Professional"),
                ],
                db_index=True,
                default=b"dr",
                max_length=2,
            ),
        ),
    ]
