# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-06-22 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reg_form", "0007_auto_20200622_0126"),
    ]

    operations = [
        migrations.CreateModel(
            name="medical_councils",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("council_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="extrafields",
            name="medical_council",
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
    ]
