# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-17 07:18
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reg_form", "0008_auto_20200622_0134"),
    ]

    operations = [
        migrations.AddField(
            model_name="extrafields",
            name="user_long_description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
