# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-31 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reg_form", "0009_extrafields_user_long_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="third_party_user_registration_log",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255)),
                ("data", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
