# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-31 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reg_form", "0010_third_party_user_registration_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="third_party_user_registration_log",
            name="status",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
