# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-09-18 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reg_form", "0011_third_party_user_registration_log_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="extrafields",
            name="user_extra_data",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
