# Generated by Django 2.2.18 on 2021-04-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_form', '0011_third_party_user_registration_log_status'),
        ('reg_form', '0006_auto_20210212_0932'),
    ]

    operations = [
    ]
