# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-11-19 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reg_form", "0012_extrafields_user_extra_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="states",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
