# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-02-26 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reg_form", "0013_states"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrafields",
            name="user_extra_data",
            field=models.CharField(blank=True, max_length=550),
        ),
    ]
