# Generated by Django 2.2.18 on 2021-04-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_form', '0012_merge_20210422_1244'),
        ('reg_form', '0014_auto_20210226_0208'),
    ]

    operations = [
    ]
