# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-03 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_extrainfo", "0002_auto_20190605_0650"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course_extrainfo",
            options={
                "verbose_name": "Course Extrainfo",
                "verbose_name_plural": "Courses Extrainfo",
            },
        ),
        migrations.AddField(
            model_name="course_extrainfo",
            name="course_seo_url",
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
