# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-03 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_extrainfo", "0003_auto_20190903_0328"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course_extrainfo",
            options={},
        ),
    ]
