# Generated by Django 2.2.18 on 2021-04-19 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_extrainfo', '0005_auto_20210212_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_extrainfo',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='specialization.specializations'),
        ),
    ]
