# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-13 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_extrainfo", "0005_course_extrainfo_mci_mandatory"),
    ]

    operations = [
        migrations.AddField(
            model_name="course_extrainfo",
            name="google_calendar_url",
            field=models.CharField(blank=True, max_length=950),
        ),
    ]
