# Generated by Django 2.2.18 on 2021-04-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_extrainfo', '0006_course_extrainfo_google_calendar_url'),
        ('course_extrainfo', '0006_auto_20210419_1045'),
    ]

    operations = [
    ]
