# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-09-18 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_extrainfo", "0006_course_extrainfo_google_calendar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="course_extrainfo",
            name="course_extradata",
            field=models.CharField(blank=True, max_length=950),
        ),
    ]
