# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-01-15 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_extrainfo", "0007_course_extrainfo_course_extradata"),
    ]

    operations = [
        migrations.AddField(
            model_name="course_extrainfo",
            name="total_webinar_hours",
            field=models.CharField(blank=True, default=1, max_length=10),
        ),
    ]
