# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-01-20 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_extrainfo", "0008_course_extrainfo_total_webinar_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="course_extrainfo",
            name="microsite_visibile_only",
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
    ]
