# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-05-04 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_extrainfo', '0009_course_extrainfo_microsite_visibile_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_extrainfo',
            name='credit_code',
            field=models.CharField(blank=True, max_length=950),
        ),
        migrations.AddField(
            model_name='course_extrainfo',
            name='credit_given_by',
            field=models.CharField(blank=True, max_length=950),
        ),
        migrations.AddField(
            model_name='course_extrainfo',
            name='credit_point',
            field=models.IntegerField(default=0),
        ),
    ]
