# Generated by Django 2.2.18 on 2021-04-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_extrainfo', '0007_merge_20210422_1244'),
        ('course_extrainfo', '0009_course_extrainfo_microsite_visibile_only'),
    ]

    operations = [
    ]
