# Generated by Django 2.2.18 on 2021-06-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_extrainfo', '0010_merge_20210423_1128'),
        ('course_extrainfo', '0010_auto_20210504_0547'),
    ]

    operations = [
    ]
