# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-09 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webform", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webform",
            name="courseid",
            field=models.CharField(
                max_length=100, unique=True, verbose_name=b"Courseid"
            ),
        ),
    ]
