# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-02 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webform", "0002_auto_20190809_0201"),
    ]

    operations = [
        migrations.AddField(
            model_name="webform",
            name="email",
            field=models.CharField(default="", max_length=100, verbose_name=b"Email"),
            preserve_default=False,
        ),
    ]
