# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-04-02 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webform", "0003_webform_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webform",
            name="email",
            field=models.CharField(blank=True, max_length=100, verbose_name=b"Email"),
        ),
    ]
