# Generated by Django 2.2.18 on 2021-02-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webform", "0004_auto_20200402_0112"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webform",
            name="courseid",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Courseid"
            ),
        ),
        migrations.AlterField(
            model_name="webform",
            name="email",
            field=models.CharField(blank=True, max_length=100, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="webform",
            name="feedback_form_link",
            field=models.CharField(max_length=500, verbose_name="Feedback Form Link"),
        ),
        migrations.AlterField(
            model_name="webform",
            name="location",
            field=models.CharField(max_length=200, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="webform",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="webform",
            name="question",
            field=models.CharField(max_length=200, verbose_name="Question"),
        ),
        migrations.AlterField(
            model_name="webform",
            name="sheeturl",
            field=models.CharField(max_length=300, verbose_name="Url"),
        ),
    ]
