# Generated by Django 2.2.18 on 2021-02-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hcspecialization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hcspecializations",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Hcspecialization"),
        ),
    ]
