# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-08 06:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0013_organization_org_promo_video"),
        ("add_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="associations_ad_manager",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_id",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name=b"Course ID"
                    ),
                ),
                ("image_url", models.CharField(blank=True, max_length=250)),
                ("video_url", models.CharField(blank=True, max_length=250)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Association ad",
                "verbose_name_plural": "Associations ads",
            },
        ),
        migrations.AlterField(
            model_name="user_view_counter",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
