# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-13 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("add_manager", "0002_auto_20190808_0247"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_view_counter",
            name="mcounter",
            field=models.CharField(db_index=True, default=0, max_length=255),
            preserve_default=False,
        ),
    ]
