# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-13 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("add_manager", "0003_user_view_counter_mcounter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_view_counter",
            name="mcounter",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
