# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-13 12:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("add_manager", "0004_auto_20200113_0708"),
    ]

    operations = [
        migrations.AddField(
            model_name="associations_ad_manager",
            name="date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="associations_ad_manager",
            name="disclaimer",
            field=models.TextField(blank=True),
        ),
    ]
