# Generated by Django 2.2.18 on 2021-04-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("add_manager", "0006_disclaimer_agreement_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="associations_ad_manager",
            name="course_id",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Course ID"
            ),
        ),
    ]
