# Generated by Django 2.2.18 on 2021-02-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_us", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact_us_form",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
    ]
