# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-07-28 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_custom_email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_mail_to_users',
            name='course_id',
            field=models.CharField(blank=True, default='N/a', max_length=128),
        ),
    ]
