# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-11 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="specializations",
            name="image",
            field=models.CharField(
                default="NULL", max_length=500, verbose_name=b"Image"
            ),
            preserve_default=False,
        ),
    ]
