# Generated by Django 2.2.18 on 2021-02-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialization", "0002_specializations_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializations",
            name="image",
            field=models.CharField(max_length=500, verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="specializations",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Specialization"),
        ),
    ]
