# Generated by Django 2.2.18 on 2021-02-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_study", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case_study_abstracts",
            name="case_study_type",
            field=models.CharField(
                choices=[
                    (
                        "Observational (non-experimental) studies",
                        (
                            ("chrt-stds", "Cohort studies"),
                            ("case-cntrl", "Case control studies"),
                            ("rdbs", "Routine-data-based studies"),
                            ("drs", "Dose-response studies"),
                        ),
                    ),
                    (
                        "Intervention (experimental) studies",
                        (
                            ("cl", "Clinical trials"),
                            ("fli", "Field trials(individual level)"),
                            ("fla", "Field trials(aggregated level)"),
                        ),
                    ),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="case_study_abstracts",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("dr", "Doctor"),
                    ("prof", "Professor"),
                    ("std", "Student"),
                    ("team", "Team"),
                ],
                db_index=True,
                default="dr",
                max_length=5,
            ),
        ),
    ]
