# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-01-13 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="user_session_tracking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(max_length=128)),
                (
                    "course_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("course_id", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "module_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "sub_module_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("pagein", models.DateTimeField(auto_now_add=True)),
                ("pageout", models.DateTimeField(auto_now=True)),
                (
                    "track_updated",
                    models.IntegerField(blank=True, default=0, max_length=5, null=True),
                ),
            ],
        ),
    ]
