# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-06 05:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocmodeNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "message",
                    models.TextField(
                        blank=True, max_length=255, null=True, verbose_name="Message"
                    ),
                ),
                (
                    "redirection_type",
                    models.CharField(
                        choices=[
                            (b"disscussion", b"Disscussion"),
                            (b"email_digest", b"Email Digest"),
                            (b"instructor", b"Instructor Communication"),
                            (b"recuring_nudge", b"Recuring Nudge"),
                            (b"start_date", b"start Date"),
                            (b"before_days", b"Before Days"),
                            (b"course_created", b"Course Created"),
                        ],
                        default=b"start_date",
                        max_length=255,
                        verbose_name=b"Redirection",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (b"draft", b"Draft"),
                            (b"running", b"Running"),
                            (b"error", b"Error"),
                            (b"sent", b"Sent"),
                        ],
                        default=b"begin",
                        max_length=10,
                        verbose_name=b"Status",
                    ),
                ),
                ("scheduled_time", models.DateTimeField(blank=True, null=True)),
                (
                    "course_id",
                    opaque_keys.edx.django.models.CourseKeyField(
                        db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="notification_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notifications",
            },
        ),
        migrations.CreateModel(
            name="DocmodeNotificationMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "message",
                    models.TextField(
                        blank=True, max_length=255, null=True, verbose_name="Message"
                    ),
                ),
                (
                    "redirection_type",
                    models.CharField(
                        choices=[
                            (b"disscussion", b"Disscussion"),
                            (b"email_digest", b"Email Digest"),
                            (b"instructor", b"Instructor Communication"),
                            (b"recuring_nudge", b"Recuring Nudge"),
                            (b"start_date", b"start Date"),
                            (b"before_days", b"Before Days"),
                            (b"course_created", b"Course Created"),
                        ],
                        default=b"start_date",
                        max_length=255,
                        verbose_name=b"Redirection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Message",
            },
        ),
        migrations.CreateModel(
            name="MobileDiviseDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "mobile_device_token",
                    models.CharField(blank=True, max_length=3000, null=True),
                ),
                (
                    "mobile_device_id",
                    models.CharField(blank=True, max_length=3000, null=True),
                ),
                (
                    "mobile_version",
                    models.CharField(blank=True, max_length=3000, null=True),
                ),
                (
                    "mobile_device_type",
                    models.CharField(blank=True, max_length=3000, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MobileDiviseDetail",
            },
        ),
    ]
