# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-06 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("push_notification", "0002_auto_20190806_0215"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="docmodenotification",
            name="users",
        ),
    ]
