# Generated by Django 2.2.18 on 2021-02-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "push_notification",
            "0005_docmodenotificationcourse_docmodenotificationemail",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="docmodenotification",
            name="redirection_type",
            field=models.CharField(
                choices=[
                    ("disscussion", "Disscussion"),
                    ("email_digest", "Email Digest"),
                    ("instructor", "Instructor Communication"),
                    ("recuring_nudge", "Recuring Nudge"),
                    ("start_date", "start Date"),
                    ("before_days", "Before Days"),
                    ("course_created", "Course Created"),
                ],
                default="start_date",
                max_length=255,
                verbose_name="Redirection",
            ),
        ),
        migrations.AlterField(
            model_name="docmodenotification",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("running", "Running"),
                    ("error", "Error"),
                    ("sent", "Sent"),
                ],
                default="begin",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="docmodenotificationcourse",
            name="redirection_type",
            field=models.CharField(
                choices=[
                    ("disscussion", "Disscussion"),
                    ("email_digest", "Email Digest"),
                    ("instructor", "Instructor Communication"),
                    ("recuring_nudge", "Recuring Nudge"),
                    ("start_date", "start Date"),
                    ("before_days", "Before Days"),
                    ("course_created", "Course Created"),
                ],
                default="start_date",
                max_length=255,
                verbose_name="Redirection",
            ),
        ),
        migrations.AlterField(
            model_name="docmodenotificationcourse",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("running", "Running"),
                    ("error", "Error"),
                    ("sent", "Sent"),
                ],
                default="begin",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="docmodenotificationemail",
            name="redirection_type",
            field=models.CharField(
                choices=[
                    ("disscussion", "Disscussion"),
                    ("email_digest", "Email Digest"),
                    ("instructor", "Instructor Communication"),
                    ("recuring_nudge", "Recuring Nudge"),
                    ("start_date", "start Date"),
                    ("before_days", "Before Days"),
                    ("course_created", "Course Created"),
                ],
                default="start_date",
                max_length=255,
                verbose_name="Redirection",
            ),
        ),
        migrations.AlterField(
            model_name="docmodenotificationemail",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("running", "Running"),
                    ("error", "Error"),
                    ("sent", "Sent"),
                ],
                default="begin",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="docmodenotificationmessage",
            name="redirection_type",
            field=models.CharField(
                choices=[
                    ("disscussion", "Disscussion"),
                    ("email_digest", "Email Digest"),
                    ("instructor", "Instructor Communication"),
                    ("recuring_nudge", "Recuring Nudge"),
                    ("start_date", "start Date"),
                    ("before_days", "Before Days"),
                    ("course_created", "Course Created"),
                ],
                default="start_date",
                max_length=255,
                verbose_name="Redirection",
            ),
        ),
    ]
